### ISSUE TITLE
xposed can not write to file

### ISSUE THREAD

**Issue by OhYee** [android-hacker/exposed#1]
android 7.0
samsung c5

![screenshot_20171202-104442](https://user-images.githubusercontent.com/13498329/33510949-9ea1c962-d6d8-11e7-8022-04193c693aa6.png)

**Comment by supereweteam-at-gmail** [comment]
@OhYee 这个在正常root的手机上 不使用va可以运行吗

**Comment by tiann** [comment]
@OhYee 你的这个XposedInstaller是从双开中启动的吗？

**Comment by OhYee** [comment]
@tiann 是在双开里启动的
不过不知道是不是xposed本身的问题，我之前root的时候都是单独下的xposed包才能用，installer下的不能用

**Comment by OhYee** [comment]
@supereweteam-at-gmail
大部分手机应该都没问题把，不过一般都是recovery刷进去把

**Comment by BackTrackCRoot** [comment]
三星 s7同样有问题

**Comment by tiann** [comment]
模块管理，暂时有问题，请关注下个版本。

**Comment by OhYee** [comment]
好的，期待下个版本，感谢
