### ISSUE TITLE
Qx 模块

### ISSUE THREAD

**Issue by Minelu** [android-hacker/exposed#12]
激活Qx模块后，Tim 和QQ闪退打不开
Android8.1 LG G3 lineageOS15.1 unofficial

**Comment by tiann** [comment]
@Minelu 已知问题，正在解决中。

**Comment by tiann** [comment]
可以用[QQ精简模块](https://www.coolapk.com/apk/qiwu.qq_simplity)

QX的问题比较复杂，不会专门去修复。
