### ISSUE TITLE
什么时候可以支持内存或sd卡安装应用

### ISSUE THREAD

**Issue by HugoTan** [android-hacker/exposed#13]
大概计划...

**Comment by tiann** [comment]
＋号不是有三个TAB么，里面没有东西吗？

**Comment by HugoTan** [comment]
是的，点进去什么都没有，android7.1.1 samsung note8港版系统，之前的版本也是一样

**Comment by tiann** [comment]
确认/sdcard/目录下面有apk文件吗？

**Comment by HugoTan** [comment]
要放到根目录下就找到了，谢谢

**Comment by HugoTan** [comment]
找到了，安装应用后打开黑屏了，克隆的app正常

**Comment by tiann** [comment]
@HugoTan 0.2.8版本不需要放在根目录了，试下新版安装之后是否黑屏？

**Comment by HugoTan** [comment]
0.2.8测试反馈：
有部分的APP从SD卡安装后黑屏，克隆没问题，比如apkpure

**Comment by tiann** [comment]
0.3.7版本是否海存在此问题？

**Comment by HugoTan** [comment]
安装应该打开都没问题，有些功能点进去会黑屏，比如说apkpure的应用管理，因为会去扫描存储，可能导致黑屏

**Comment by tiann** [comment]
apkpure 是另外的问题，与本issue无关；这个先close。
