### ISSUE TITLE
0.2.8体验感受（建议）

### ISSUE THREAD

**Issue by HugoTan** [android-hacker/exposed#14]
感谢作者的付出，0.2.8的流畅性更好了，问题也越来越少了，但有些地方还想提出一些个人建议：
1、更新完成后本地安装包自动删除，如果出现问题卸载再安装这将意味着我们只能去网上下载0.2.7版本的安装包，然后再升级（当然，作者本身可能有自己的考虑），如果可以的话能否本地保存一下安装文件呢？
2、0.2.8在上一版本上去掉了虚拟定位，个人认为，使用该APP的人员不仅仅是双开的需求（至少我个人不完全是），我更想在APP稳定后把所有国产的APP都放到里面进行管控，像虚拟位置、虚拟手机信息等等更能保护个人隐私（开启google now也更加方便）。当然xposed本身有很多插件可以支持，但xposed插件很“多年久失修”，而且VAExposed本身自带这些功能的话，更加能确保稳定性，减少对插件依赖。
3、VAExposed在运行的时候在通知栏会出现“VAExposed正在运行，触控来取得更多信息，或停止应用程序”，这不是0.2.8才出现的，应该是可以去掉的。像国际版的QQ（play上）也是类似，国内版的则没有。
4、等APP成熟稳定后建议增加捐赠，当然开发者本意可能不是为了这些，我只是表达用户的一点诚意。
以上纯属个人建议，相信您有自己的开发方向，合理的还望采纳（尤其第二点），多谢！

**Comment by tiann** [comment]
@HugoTan 首先感谢提出这么多宝贵的意见，我说下自己的看法：
1. 第一点，下个版本就可以改掉；这个没有特殊考虑。
2. 虚拟定位是VA原有的功能，但是它并不完善；我的想法是用插件来实现这个功能。你说的XP插件年久失修，这个不是问题，我可以暂时把VA里面原有的虚拟定位功能做成一个插件来使用（可能要等几个版本）
3. 这个我个人理解，是为了提升VAExposed进程的优先级，保护VAExposed进程不被系统杀死的；一旦VAExposed服务进程被杀，程序工作就会不正常；这是为了使用它需要付出的一点代价。
4. 当务之急是解决各种问题，捐赠的话以后再考虑 :) 谢谢。

**Comment by HugoTan** [comment]
多谢
第二点虚拟定位我用过，感觉还不错，最好下一个版本还是保存该功能，后期如果改的话再变。最好以后还能增加虚拟手机信息（和xprivacy类似），国内很多应用不给权限不让用，给了又有隐私和安全问题。
第三点我觉得自android7.0后有个电池优化，可以弹框提醒用户不让系统实行电池优化，我在用tasker就会弹个框出来让我确认是否电池优化。

**Comment by HugoTan** [comment]
对了，我看以前版本还有除了虚拟定位还有存储什么的，以前的打算是虚拟存储吗？有的话更好了，这样还能对VAExposed内的APP做进一步保护

**Comment by HugoTan** [comment]
现有在线的更新机制是打开APP自动去联网进行更新，这意味着每次打开APP的时候都要去联网检查更新，并且用户不能确认，能否改成手动检查更新或提醒更新呢？

**Comment by tiann** [comment]
去掉前台通知那个我需要在考虑一下，谢谢建议。

虚拟存储是VA原本打算的功能，我这边暂时没有开发计划（等基本功能完善了再说）
现在处于内测阶段，需要快速验证和反馈各种问题，更新比较频繁，后期改成手动更新或者提醒的方式。

**Comment by tiann** [comment]
1. 前台通知不能去掉；去掉很容易被杀，无法正常使用。
2. 机型伪装可以用应用变量插件。
3. 位置伪装可以用一些模拟位置插件，比如lataclysm，fakemap等。
4. 提示电池优化的功能已经加上，谢谢建议。https://github.com/android-hacker/VAExposed/commit/05fbe12dc06f738654fb21cf87c3d6f689352d6d
