### ISSUE TITLE
android6.0中微X和QX插件激活后不起作用

### ISSUE THREAD

**Issue by githubnimabi** [android-hacker/exposed#15]
你好，我手机是LG H868(国行版LG G5) android6.0 
我在手机上安装VAExposed(0.2.8 (Build 28)更新于20180108)之后，先把系统中安装的微信(6.5.13)复制到了VA中，登录VA中的微信之后，又把微X(1.16)复制到了VA中，在VA自带的Xposed管理器中我激活了微X，但是不管怎样重启(手动重启手机和VA中重启都试过)，VA中的微信打开之后，都找不到微X的设置界面，也就是说微X虽然在Xposed管理器中激活了，但是却没有起作用。。  同样，我复制QQ和QX到VA中，依旧是这种问题。我看到有人发表QX有问题，并且开发者也说已经在解决了，但是我想把问题描述的详细些，我个人是android开发，但是只了解些android的皮毛，如果需要远程测试或者提供些相关支持，我都愿意。最终，希望开发者能尽快解决这些问题。
另外，我个人非常喜欢VAExposed，它实现不能解锁BL、不能root、不能装Xp手机的玩机梦想，而且最近的版本中，apk不管在那个目录下，都能被找到并且免安装复制到VA中，真的很感谢VA！
最后一个问题，如果我提供Log，请问，Log日志在哪里？是必须把VA项目通过AS运行起来，才能看到还是说只要手机中装了VA，就能在手机的文件管理器中找到？

**Comment by tiann** [comment]
@githubnimabi 正在努力解决中，感谢关注。

log的话，不用用AS运行起来，有Android SDK就可以，直接 adb logcat -v time 即可。

**Comment by githubnimabi** [comment]
@tiann 好的，多谢指导

**Comment by tiann** [comment]
WX已经解决，QX的问题见 #12

**Comment by githubnimabi** [comment]
辛苦了！！非常感谢！！0.42的版本我用了，wx已经能用了，但是还是会时不时的卡顿直至卡死，，等我装上0.43的试试，哈哈，好期待，再次表示感谢~~
