### ISSUE TITLE
几个小问题/bug/建议

### ISSUE THREAD

**Issue by hlc1134** [android-hacker/exposed#18]
手机三星s7e，Android 7.0，微信6.6.1，微信巫师2.6.2，vaexposed版本0.2.9
1、微信无法保存图片到本机，手机相册里看不到。
2、微信无法调用“其他应用打开”，点按无任何反应，即使我把WPS装到vaexposed中。
3、微信软件不定时freezing，只能在vaexposed中按重启。

我不知道以上某些是bug还是vaexposed本身的特性。不过如果能改善的话，可以提高体验。

谢谢！

**Comment by tiann** [comment]
第三个问题已经修复，其他两个可能需要等一段时间。

**Comment by hlc1134** [comment]
更新到0.3.2，依旧存在微信冻结问题

**Comment by hlc1134** [comment]
又发现了问题。
微信出现freezing，在vae中重启之后，微信巫师会失效，在installer中停用启用和在vae中重装微信巫师软件均无用。我目前只能在手机中清除vae的应用数据，再把所有软件全部重装一遍，才能又有用。

**Comment by hlc1134** [comment]
更新到0.3.7
依旧存在微信巫师失效的问题。具体表现为只有刚装好微信第一次打开时，微信巫师有效果。之后所有情况下打开微信，无论是各种重启、在installer中打开关闭插件，都无法重新使得微信巫师有效果。

如果需要配合上传log的请直接联系我。

**Comment by tiann** [comment]
微信freezing的问题在 0.4.2 版本是否出现？
另外用的是微信巫师支持的版本吗？

**Comment by hlc1134** [comment]
> 微信freezing的问题在 0.4.2 版本是否出现？另外用的是微信巫师支持的版本吗？

已经不再出现freezing了。巫师用的是2.6.2，配合微信6.5.22，是写在支持列表中的版本。

**Comment by hlc1134** [comment]
@tiann 已经不再出现freezing了。巫师用的是2.6.2，配合微信6.5.22，是写在支持列表中的版本。

**Comment by BackTrackCRoot** [comment]
我之前也遇到过 微信第一次有效 之后就没用的…… 然后这次重装微信巫师 直接打不开了
