### ISSUE TITLE
能否实现vpn代理

### ISSUE THREAD

**Issue by sqliuchang** [android-hacker/exposed#19]
偶然在设置－更多设置－vpn中发现有VAExposed，于是我在应用内安装了一个vpn软件，打开时出现网络连接请求，确认后并无法实现代理，而是连接失败。
既无法实现VAExposed内部软件的网络代理，也无法实现手机全局代理。

**Comment by tiann** [comment]
暂时没有精力做这个。

**Comment by sqliuchang** [comment]
好的呢,没大问题,多谢
但是今天更新完之后TIM在QX模块下闪退...之前还可以用的

2018-01-17 16:57 GMT+08:00 weishu <notifications@github.com>:
