### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by HugoTan** [android-hacker/exposed#20]
这个软件和virtualapp(已停止更新并商业化为罗盒多开)有什么关系吗?
能否登陆play商店呢?

**Comment by tiann** [comment]
这个软件是基于[VirtualApp](https://github.com/asLody/VirtualApp) 和 [epic](https://github.com/tiann/epic)；双开部分的核心代码完全源自VirtualApp。

不会登陆play商店。

（play以后也不允许动态加载代码类的APP上架吧）

**Comment by HugoTan** [comment]
现在virtualapp商业化了，会不会影响这个项目呢

**Comment by HugoTan** [comment]
现在virtualapp还进驻play商店了

**Comment by tiann** [comment]
目前来看不会。

Exposed是设计给双开框架使用的，对双开的具体实现没有要求。只是如果VirtualApp不允许使用，重新实现双开框架会略微费点时间。

**Comment by tiann** [comment]
这个是必须加的，以后一定会加。

**Comment by HugoTan** [comment]
好的，多谢。虚拟定位大概什么时候可以出来?我们公司开始定位打卡了，哈哈

**Comment by tiann** [comment]
只能说，没有确切时间。
