### ISSUE TITLE
Can not get classLoader of app

### ISSUE THREAD

**Issue by ssddi456** [android-hacker/exposed#22]
```
public class XposedMod implements IXposedHookLoadPackage {
    public void handleLoadPackage(LoadPackageParam lpparam) throws Throwable {
        final String packageName = lpparam.packageName.toString();
        XposedBridge.log("Loaded app: " + packageName);

        if (lpparam.classLoader != null) {
            XposedBridge.log("this app has loader");
        }
  }
}
```
I cannot see the log "this app has loader" even on very simple demo app

devices:
android 5.1   HUAWEI TAG-AL00
Android 7.1.1  OnePlus 3T

**Comment by tiann** [comment]
Did you check the module in XposedInstaller's module settings?

**Comment by ssddi456** [comment]
I can see this log ` XposedBridge.log("Loaded app: " + packageName);`

**Comment by tiann** [comment]
Change your log to ```XposedBridge.log("Loaded app: " + packageName + " classloader: " + lpparam.classLoader);``` to see if it is null really?

**Comment by ssddi456** [comment]
nope, it is  null.
```
01-22 00:31:43.396 I/Xposed  (21271): Loaded app: ApplicationInfo{7d6138b de.robv.android.xposed.installer} classloader: null
```

**Comment by ssddi456** [comment]
so what i can do to find out why it is null?

**Comment by tiann** [comment]
I write a simple plugin and this works well on my device(Xiaomi 4), this seems strange;
could you please show your detail operation procedure (or upload your demo plugin)?
