### ISSUE TITLE
安装Xprivacy Lua之后卡死

### ISSUE THREAD

**Issue by xiocode** [android-hacker/exposed#23]
手机: Sony XZ Premium
系统: Android 8.0
软件版本: VAExposed 0.4.2

问题描述:
尝试安装Xprivacy Lua，在Home页面重启之后，打开Xprivacy Lua会报Module没有激活，然后VAExposed打开也会卡死无法操作。

**Comment by tiann** [comment]
这个模块还没有稳定版吧？

**Comment by xiocode** [comment]
@tiann 是的，没有稳定版。。因为没有日志，我也不确定是什么问题，那么请先暂时忽略吧！

**Comment by tiann** [comment]
大致看了一下，XPrivacy Lua Hook了Application的某个方法，导致Application无法创建。等它稳定了我再修复一波吧。

**Comment by xiocode** [comment]
好的，谢谢。
