### ISSUE TITLE
关于编译问题

### ISSUE THREAD

**Issue by zcadqewxs** [android-hacker/exposed#25]
我编译源码时候显示 Error:Failed to resolve: me.weishu:epic:0.4.4，然后根据大大的提示，使用了0.3.5的版本
compile ('me.weishu:epic:0.3.5')
再编译的时候提示
---
Error:(41, 30) 错误: 找不到符号
符号:   类 DexposedBridge
位置: 程序包 de.robv.android.xposed
---
没有这个类 ”import de.robv.android.xposed.DexposedBridge;“

请问应该怎么解决？谢谢~

**Comment by tiann** [comment]
在VAExposed项目中依赖 exposed-core的时候，用：
me.weishu.exposed:exposed-core:0.3.5
