### ISSUE TITLE
三星S7 edge 框架显示未安装

### ISSUE THREAD

**Issue by BackTrackCRoot** [android-hacker/exposed#3]
三星S7 7.0 （在VA里面打开后）
Xposed 框架未安装。
Xposed 与您的ROM 似乎存在已知的问题("wrong
base directory: /data/user/0/io.virtualapp/virtual/
data/user/0/de.robv.android.xposed.installer
一/data/data/io.virtualapp/virtual/data/user/0/
de.robv.android.xposed.installer")。安装Xposed
可能无法工作或引发严重问题。点击此处获知问题详
情。

然后Xposed 日志也出问题，无法写入日志，提示没有该文件。

**Comment by tiann** [comment]
[epic](https://github.com/tiann/epic) 里面的测试case能通过吗？

**Comment by BackTrackCRoot** [comment]
我尝试编译epic，但是好像出现了依赖错误，不知您是否方便提供一个编译版本呢？多谢！

**Comment by tiann** [comment]
[app-release.apk.zip](https://github.com/android-hacker/exposed/files/1541339/app-release.apk.zip)

**Comment by BackTrackCRoot** [comment]
![28b293f7f14d81c17742bc5cb2be0878](https://user-images.githubusercontent.com/4964761/33752860-236b3188-dc1f-11e7-99c1-2c21a37071d1.png)

**Comment by tiann** [comment]
上面的那些case呢？

**Comment by BackTrackCRoot** [comment]
有几率通过第一个 然后其他……都不能通过 只有自定义的才行

**Comment by tiann** [comment]
嗯 ，Hook框架的问题。我没有三星手机，等我找个三星手机看下。

**Comment by BackTrackCRoot** [comment]
thanks！

**Comment by tiann** [comment]
[0.1.7.apk.zip](https://github.com/android-hacker/exposed/files/1547030/0.1.7.apk.zip)

@wuxianlin 试试这个

**Comment by zhangyiran** [comment]
是因为VA只提供了32位环境，而epic只支持64位。

**Comment by tiann** [comment]
@zhangyiran 不是的，epic也支持32位。

**Comment by tiann** [comment]
新版已经没问题了，Close。
