### ISSUE TITLE
希望可以支持apk文件的打开方式

### ISSUE THREAD

**Issue by Minelu** [android-hacker/exposed#30]
[就是点击apk文件后，像容器一样支持安装至VirtualXposed

**Comment by Minelu** [comment]
图片http://ci.baidu.com/c4hWGc8GEI

**Comment by tiann** [comment]
这个功能几个版本前就支持了的，点那个浮动按钮 ➕

**Comment by Minelu** [comment]
我的意思是在主系统点击apk后 会出现一个 [列表](http://ci.baidu.com/j3ZhGXJA88) ，希望在这个列表中添加VirtualXposed

**Comment by tiann** [comment]
锦上添花的功能，目前VXP的主要问题不是这个；等稳定性更好了再说。

**Comment by Minelu** [comment]
那好叭，作者大大加油哦(^_^)

**Comment by vipzrx** [comment]
@Minelu
百度图床的连接不能直接显示,连接点击去也是失效
![20180320_132331](https://user-images.githubusercontent.com/5094958/37637320-f00a8fbe-2c41-11e8-9c80-7db0695470cb.png)

 github的issue支持图片.

添加图片方法:将图片拖放到到编辑框中,就会自动生成外联,可以直接显示图片

**Comment by vipzrx** [comment]
@tiann
github支持标签和project功能
可以将功能建议,反馈,以及progect的进展标注不同标签
github的project使用的是看板模型,可以设定优先级,同时自动连接issue的和状态

**Comment by tiann** [comment]
@vipzrx 谢谢建议，我关注一下这个功能。

**Comment by tiann** [comment]
fixed: https://github.com/android-hacker/VirtualXposed/commit/6ba15d84686d2dbb5a379a67ef424355d612d33f
