### ISSUE TITLE
通过这个应用快速开发xposed插件

### ISSUE THREAD

**Issue by l15y** [android-hacker/exposed#31]
希望提供安装应用、重新启动的接口

**Comment by tiann** [comment]
你指的接口，是哪种形式的？
目前不是已经可以安装，重启了吗

**Comment by l15y** [comment]
目前的功能需要手动点击，浪费时间，虽然比重启系统节约时间，但需要复杂的操作，不适合开发时的反复调试。希望有命令行形式的接口

**Comment by tiann** [comment]
嗯，可以考虑加一个Receiver。

**Comment by l15y** [comment]
还有另一种思路，实现起来应该更简单，也不需要学习新的东西：检测到内部已安装应用在外部更新，自动更新内部的，如果更新的应用是插件就自动重启

**Comment by l15y** [comment]
对于普通用户，这个功能也是实用的

**Comment by tiann** [comment]
自动更新不稳定，不会加。也并没有比Receiver简单。
首先，VXP目前安装APK时间较长，不让用户在前台等待而后台静默更新如果更新过程中被杀就会不正常。
其次，不是所有的用户都希望有自动更新这个功能；虽然可以加开关给用户选择，但无太大必要。

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/wiki/Utilities-For-Xposed-Module-Developer

看看这个是否能满足要求。

**Comment by tiann** [comment]
本问题已经解决；用户接口参见 https://github.com/android-hacker/exposed/issues/34
