### ISSUE TITLE
VirtualXposed下微信的缺失功能反馈

### ISSUE THREAD

**Issue by sicifus** [android-hacker/exposed#32]
1. 聊天记录的图片、视频似乎无法保存。
2. 小程序 -> 添加到桌面，只能在VAE的桌面看到快捷方式，无法进一步添加到原生桌面下。
3. 多开的微信无法在原生桌面下添加快捷方式，提示“微信(VAE)快捷方式已存在”。（其实不算微信的功能缺失，顺便一起提一下了）

运行环境：
华为荣耀8，EMUI 5.0.1（Android 7.0）。
谢谢！

**Comment by tiann** [comment]
第三个和第二个问题很快就会修复，第一个可能需要等一段时间（也不一定）；感谢反馈。

**Comment by tiann** [comment]
第三个问题 0.7.0 已经修复了；第二个问题再等等。

**Comment by sicifus** [comment]
神速，感谢！

**Comment by tiann** [comment]
快捷方式已修复：https://github.com/android-hacker/VirtualXposed/commit/6273d244a435935d6952fc81c9212202b069419e

视频问题已修复：https://github.com/android-hacker/VirtualXposed/commit/b947cb2af700879e3aa7b1e774c20920a8511f29
