### ISSUE TITLE
VirtualXposed Gradle更新失败

### ISSUE THREAD

**Issue by cnsheds** [android-hacker/exposed#36]
首先请原谅我在这里发关于VirtualXPosed的问题, 是因为那边没办法发问题
VirtualXPosed 这个模块无法同步,
 Failed to resolve: me.weishu.exposed:exposed-core:0.5.0
麻烦大大看一下呢, 谢谢

**Comment by tiann** [comment]
版本号修改为 0.3.5试一下

**Comment by cnsheds** [comment]
改为0.3.5可以了, 谢谢
