### ISSUE TITLE
不能编译

### ISSUE THREAD

**Issue by rover12421** [android-hacker/exposed#37]
Failed to resolve: me.weishu:epic:0.5.0

依赖库找不到

**Comment by tiann** [comment]
refer:  https://github.com/android-hacker/exposed/issues/36

**Comment by rover12421** [comment]
使用0.3.6一样报错

Error:(39, 30) error: cannot find symbol class DexposedBridge
Error:(264, 45) error: cannot find symbol variable DexposedBridge
Error:(313, 9) error: cannot find symbol variable DexposedBridge
Error:(320, 9) error: cannot find symbol variable DexposedBridge
Error:(331, 9) error: cannot find symbol variable DexposedBridge
Error:(341, 9) error: cannot find symbol variable DexposedBridge
Error:(354, 9) error: cannot find symbol variable DexposedBridge
Error:(395, 9) error: cannot find symbol variable DexposedBridge

0.3.6  没有 `de.robv.android.xposed.DexposedBridge`

**Comment by rover12421** [comment]
好了
0.3.6不行
0.3.5 正常。。。

**Comment by rover12421** [comment]
0.3.5/0.3.6都测试果了，都不行

如果把 `de.robv.android.xposed.DexposedBridge`
修改成原来的`com.taobao.android.dexposed.DexposedBridge`
但是下面的`XC_MethodHook`包又不对
```
public static XC_MethodHook.Unhook hookMethod(Member method, XC_MethodHook callback) {
        if (ignoreHooks(method)) {
            return null;
        }
        final XC_MethodHook.Unhook unhook = DexposedBridge.hookMethod(method, callback);
        return ExposedHelper.newUnHook(callback, unhook.getHookedMethod());
    }
```

希望能发布一个epic新版本

**Comment by tiann** [comment]
exposed-core 0.3.6 并非 epic 0.3.6

**Comment by rover12421** [comment]
我是同步最新的 exposed-core 编译的
你的意思是不要使用新的 exposed-core？

**Comment by tiann** [comment]
要编译VirtualXposed，不需要编译 exposed
