### ISSUE TITLE
075和077版本还是闪退

### ISSUE THREAD

**Issue by githubnimabi** [android-hacker/exposed#38]
首先感谢大佬的辛劳，但是不得不说，我这手机用了vxp之后，一直有莫名其妙的闪退问题

手机是LG H868 android6.0 
微信是6.5.13
VXP用过073 075 077
微X是1.18

自从vxp能用微X之后，我就一直在用vxp，大概从045版本开始吧，但是从一开始一直到现在，一直都存在一些 不必现 的闪退。
1.有时候是和别人聊天，在给对方打字的时候突然闪退
2.有时候是刚点开vxp里的微信，然后就闪退
3.有时候是在微信的聊天列表中不闪退，但是别人给我发个小视频或者发一个表情，然后只要我从列表点进去，一点就会崩掉，但是我从聊天列表点进和其他人的聊天页面时，就不会闪退
4.从一开始的vxp到现在，我手机一直不能显示vxp的通知，我看别人系统像小米的，就会显示，我的手机会显示通知的那一条，但是这条通知全是白色的，没有任何内容

以上问题，1,2,3都不是必现的，4是一直都不显示，希望能配合作者找出问题，再次感谢作者

**Comment by tiann** [comment]
用什么出现闪退？

**Comment by githubnimabi** [comment]
稍等，正在详细说明，刚才在编辑问题，想换行，结果键盘按了之后网页刷新，直接发表问题了，，哈哈，不好意思

**Comment by tiann** [comment]
1. 微x的问题，不会专门去解决。
2. 通知白条的情况，具体是什么rom？

**Comment by githubnimabi** [comment]
就是LG 官方rom，相对于华为小米这些官方rom，LG的没有没有改动太多，比较贴近aosp
