### ISSUE TITLE
meizu Mx4 Flyme 6.2.0.0A xposed installer 崩溃，插件无法hook

### ISSUE THREAD

**Issue by gtf35** [android-hacker/exposed#5]
# 开发者你好：
## 下面是我的设备信息：
> 型号：meizu mx4
> 系统： Flyme6.2.0.0A 基于Android5.1
## 发现的问题：
> 0.xposed installer崩溃 
> 1.epic点测试崩溃
> 2.微信巫师打开显示加载失败

安装包在你专栏的网盘里下的。
另外想加入开发群，可以吗。

祝工作顺利
gtf35

**Comment by gtf35** [comment]
对了，我记得epic不支持arm32。我的手机是arm32的。我看你介绍没有说。是不是这个原因？

**Comment by tiann** [comment]
@gtf35 是的，epic不支持ARM32，所以VAExposed暂时不支持ARM32的手机。我找个你这种型号的手机看下（因为手头没有这种手机，也不知道什么手机运行在ARM32下）

**Comment by gtf35** [comment]
3年前的老设备都是arm32的吧？作者辛苦了

**Comment by tiann** [comment]
@gtf35 为何close了呢？可以open着，问题解决了再close
