### ISSUE TITLE
海思处理器xpoesd模块启动失败

### ISSUE THREAD

**Issue by ivalimmb** [android-hacker/exposed#6]
VA里面装了微信 QQ 和微信巫师模块   微信和微信巫师都启动失败  QQ可以启动 但没效果  xposed日志如下  大神看看能看出什么原因吗

QQ启动(启动成功)

io.virtualapp:p0 I/DexposedBridge: Loading modules from /data/app/com.tencent.mm-1/base.apk
/io.virtualapp:p0 I/DexposedBridge: assets/xposed_init not found in the APK
io.virtualapp:p0 I/DexposedBridge: Loading modules from /data/app/com.tencent.mobileqq-1/base.apk
/io.virtualapp:p0 I/DexposedBridge: assets/xposed_init not found in the APK
/io.virtualapp:p0 I/DexposedBridge: Loading modules from /data/app/com.gh0u1l5.wechatmagician-2/base.apk
/io.virtualapp:p0 I/DexposedBridge:   Loading class com.gh0u1l5.wechatmagician.backend.WechatHook
/com.tencent.mobileqq I/DexposedBridge:   Loading class com.gh0u1l5.wechatmagician.backend.WechatResHook
/com.tencent.mobileqq I/DexposedBridge:     This class requires resource-related hooks (which are disabled), skipping it.

微信和模块启动(启动失败)

/io.virtualapp:p2 I/DexposedBridge: Loading modules from /data/app/com.tencent.mm-1/base.apk
/io.virtualapp:p2 I/DexposedBridge: assets/xposed_init not found in the APK
/io.virtualapp:p2 I/DexposedBridge: Loading modules from /data/app/com.tencent.mobileqq-1/base.apk
/io.virtualapp:p2 I/DexposedBridge: assets/xposed_init not found in the APK
/io.virtualapp:p2 I/DexposedBridge: Loading modules from /data/app/com.gh0u1l5.wechatmagician-2/base.apk
/io.virtualapp:p2 I/DexposedBridge:   Loading class com.gh0u1l5.wechatmagician.backend.WechatHook
/io.virtualapp:p2 I/DexposedBridge:   Loading class com.gh0u1l5.wechatmagician.backend.WechatResHook
/io.virtualapp:p2 I/DexposedBridge:     This class requires resource-related hooks (which are disabled), skipping it.

**Comment by ivalimmb** [comment]
ARMV8-A  64位处理器

**Comment by tiann** [comment]
与海思无关，什么手机何种系统？

**Comment by ivalimmb** [comment]
华为mate9手机  Android版本7.0  emui版本(华为定制系统)5.0.1

**Comment by tiann** [comment]
@ivalimmb 问题解决了吗？
