### ISSUE TITLE
启动app 很慢 很慢 很慢

### ISSUE THREAD

**Issue by tianqiujie** [android-hacker/exposed#7]
启动微信 要等几分钟才打开...为啥  在xposed安装器里面安装插件 等了很久 黑屏那种  一直安不了  退出重新打开 发现并没有安装成功

**Comment by tiann** [comment]
@tianqiujie 受限于当前的HOOK实现机制，安装模块的时候请耐心等待。模块安装过程中，请不要使用对应的APP。

另外，启动微信慢的问题，你安装了哪些Xposed模块？

**Comment by tiann** [comment]
受限于目前的机制，在一段时间内无法解决；添加了loading动画和提示，耐心等待即可。
