### ISSUE TITLE
Android8.1

### ISSUE THREAD

**Issue by Minelu** [android-hacker/exposed#8]
已更新0.2.1但是显示框架未激活

**Comment by tiann** [comment]
@Minelu 是原生的Android 8.1系统吗？

**Comment by tiann** [comment]
@Minelu 你应该不是原生的Android 8.1吧？

我刷了8.1的系统，是可以使用的，能否给一下详细的机型信息？

**Comment by tiann** [comment]
@Minelu 新版解决了Android O上的各种问题，能否帮忙试下？https://fir.im/2fl4

**Comment by Minelu** [comment]
@tiann 最新版好了，感谢
