### ISSUE TITLE
xposed 日志看不了.

### ISSUE THREAD

**Issue by HIjack2015** [android-hacker/exposed#9]
查看xposed日志提示:
`Cannot read 
 log/data/user/0/io.va.exposed/virtual/data/user/0/de.robv.android.xposed.installer/exposed_log/error.log (No such file or directory)`
手动创建error.log,提示变为没权限.
把所有文件和文件夹权限设为777仍然提示没权限 

/摔

**Comment by tiann** [comment]
已知问题，下版本修复。

**Comment by tiann** [comment]
@HIjack2015 已修复：https://github.com/android-hacker/VAExposed/releases
